# Generated by Django 3.2.20 on 2023-08-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='isbn',
            field=models.CharField(default='Unknown', max_length=13),
            preserve_default=False,
        ),
    ]
