# Generated by Django 3.2.20 on 2023-09-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dybqzflbo/image/upload/v1692654204/default_profile_image.png', upload_to='images/'),
        ),
    ]
