# Generated by Django 3.2.20 on 2023-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='v1694520382/Default_pfp.svg_zurque', upload_to='images/'),
        ),
    ]
