# Generated by Django 3.2.20 on 2023-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dmtxhbwvw/image/upload/v1694521723/luwp7bqvvctdhfb137hf.png', upload_to='images/'),
        ),
    ]
